<?php 
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6801b45d13d33',
	'title' => 'البرامج السياحية',
	'fields' => array(
		array(
			'key' => 'field_6801b651dde95',
			'label' => 'اسم البرنامج',
			'name' => 'اسم_البرنامج',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6801b45d15fe6',
			'label' => 'مدة البرنامج',
			'name' => 'مدة_البرنامج',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6801b4bd15fe7',
			'label' => 'السعر',
			'name' => 'السعر',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6801b4dc15fe8',
			'label' => 'تفاصيل الرحلة',
			'name' => 'الوجهات',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6801b52115fe9',
			'label' => 'صورة الغلاف',
			'name' => 'صورة_الغلاف_',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6801b682dde96',
			'label' => 'اسم المدينة',
			'name' => 'اسم_المدينة_',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'program',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6801b6d21b794',
	'title' => 'التأشيرات',
	'fields' => array(
		array(
			'key' => 'field_6801b6d207721',
			'label' => 'اسم الدولة',
			'name' => 'اسم_الدولة',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6801b6fd07722',
			'label' => 'نوع التأشيرة',
			'name' => 'نوع_التأشيرة',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6801b7b407723',
			'label' => 'المتطلبات',
			'name' => 'المتطلبات',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6801b7cd07724',
			'label' => 'مدة الاستخراج',
			'name' => 'مدة_الاستخراج',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6801b7e307725',
			'label' => 'سعر الخدمة',
			'name' => 'سعر_الخدمة',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'visa',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6801b81ac1c3b',
	'title' => 'خدمات السفر',
	'fields' => array(
		array(
			'key' => 'field_6801b81ba8172',
			'label' => 'حجز فنادق',
			'name' => 'حجز_فنادق',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6801b830a8173',
			'label' => 'تذاكر الطيران',
			'name' => 'تذاكر_الطيران',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'travelservice',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'cate', array(
	0 => 'program',
), array(
	'labels' => array(
		'name' => 'Categories',
		'singular_name' => 'Category',
		'menu_name' => 'Categories',
		'all_items' => 'All Categories',
		'edit_item' => 'Edit Category',
		'view_item' => 'View Category',
		'update_item' => 'Update Category',
		'add_new_item' => 'Add New Category',
		'new_item_name' => 'New Category Name',
		'search_items' => 'Search Categories',
		'not_found' => 'No categories found',
		'no_terms' => 'No categories',
		'items_list_navigation' => 'Categories list navigation',
		'items_list' => 'Categories list',
		'back_to_items' => '← Go to categories',
		'item_link' => 'Category Link',
		'item_link_description' => 'A link to a category',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );
} );

add_action( 'init', function() {
	register_post_type( 'visa', array(
	'labels' => array(
		'name' => 'التاشيرات',
		'singular_name' => 'تاشيرة',
		'menu_name' => 'التاشيرات',
		'all_items' => 'All التاشيرات',
		'edit_item' => 'Edit تاشيرة',
		'view_item' => 'View تاشيرة',
		'view_items' => 'View التاشيرات',
		'add_new_item' => 'Add New تاشيرة',
		'add_new' => 'Add New تاشيرة',
		'new_item' => 'New تاشيرة',
		'parent_item_colon' => 'Parent تاشيرة:',
		'search_items' => 'Search التاشيرات',
		'not_found' => 'No التاشيرات found',
		'not_found_in_trash' => 'No التاشيرات found in Trash',
		'archives' => 'تاشيرة Archives',
		'attributes' => 'تاشيرة Attributes',
		'insert_into_item' => 'Insert into تاشيرة',
		'uploaded_to_this_item' => 'Uploaded to this تاشيرة',
		'filter_items_list' => 'Filter التاشيرات list',
		'filter_by_date' => 'Filter التاشيرات by date',
		'items_list_navigation' => 'التاشيرات list navigation',
		'items_list' => 'التاشيرات list',
		'item_published' => 'تاشيرة published.',
		'item_published_privately' => 'تاشيرة published privately.',
		'item_reverted_to_draft' => 'تاشيرة reverted to draft.',
		'item_scheduled' => 'تاشيرة scheduled.',
		'item_updated' => 'تاشيرة updated.',
		'item_link' => 'تاشيرة Link',
		'item_link_description' => 'A link to a تاشيرة.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'taxonomies' => array(
		0 => 'cate',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'program', array(
	'labels' => array(
		'name' => 'برامج سياحية',
		'singular_name' => 'برنامج سياحي',
		'menu_name' => 'برامج سياحية',
		'all_items' => 'All برامج سياحية',
		'edit_item' => 'Edit برنامج سياحي',
		'view_item' => 'View برنامج سياحي',
		'view_items' => 'View برامج سياحية',
		'add_new_item' => 'Add New برنامج سياحي',
		'add_new' => 'Add New برنامج سياحي',
		'new_item' => 'New برنامج سياحي',
		'parent_item_colon' => 'Parent برنامج سياحي:',
		'search_items' => 'Search برامج سياحية',
		'not_found' => 'No برامج سياحية found',
		'not_found_in_trash' => 'No برامج سياحية found in Trash',
		'archives' => 'برنامج سياحي Archives',
		'attributes' => 'برنامج سياحي Attributes',
		'insert_into_item' => 'Insert into برنامج سياحي',
		'uploaded_to_this_item' => 'Uploaded to this برنامج سياحي',
		'filter_items_list' => 'Filter برامج سياحية list',
		'filter_by_date' => 'Filter برامج سياحية by date',
		'items_list_navigation' => 'برامج سياحية list navigation',
		'items_list' => 'برامج سياحية list',
		'item_published' => 'برنامج سياحي published.',
		'item_published_privately' => 'برنامج سياحي published privately.',
		'item_reverted_to_draft' => 'برنامج سياحي reverted to draft.',
		'item_scheduled' => 'برنامج سياحي scheduled.',
		'item_updated' => 'برنامج سياحي updated.',
		'item_link' => 'برنامج سياحي Link',
		'item_link_description' => 'A link to a برنامج سياحي.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'taxonomies' => array(
		0 => 'cate',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'travelservice', array(
	'labels' => array(
		'name' => 'خدمات السفر',
		'singular_name' => 'خدمةالسفر',
		'menu_name' => 'خدمات السفر',
		'all_items' => 'All خدمات السفر',
		'edit_item' => 'Edit خدمةالسفر',
		'view_item' => 'View خدمةالسفر',
		'view_items' => 'View خدمات السفر',
		'add_new_item' => 'Add New خدمةالسفر',
		'add_new' => 'Add New خدمةالسفر',
		'new_item' => 'New خدمةالسفر',
		'parent_item_colon' => 'Parent خدمةالسفر:',
		'search_items' => 'Search خدمات السفر',
		'not_found' => 'No خدمات السفر found',
		'not_found_in_trash' => 'No خدمات السفر found in Trash',
		'archives' => 'خدمةالسفر Archives',
		'attributes' => 'خدمةالسفر Attributes',
		'insert_into_item' => 'Insert into خدمةالسفر',
		'uploaded_to_this_item' => 'Uploaded to this خدمةالسفر',
		'filter_items_list' => 'Filter خدمات السفر list',
		'filter_by_date' => 'Filter خدمات السفر by date',
		'items_list_navigation' => 'خدمات السفر list navigation',
		'items_list' => 'خدمات السفر list',
		'item_published' => 'خدمةالسفر published.',
		'item_published_privately' => 'خدمةالسفر published privately.',
		'item_reverted_to_draft' => 'خدمةالسفر reverted to draft.',
		'item_scheduled' => 'خدمةالسفر scheduled.',
		'item_updated' => 'خدمةالسفر updated.',
		'item_link' => 'خدمةالسفر Link',
		'item_link_description' => 'A link to a خدمةالسفر.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'taxonomies' => array(
		0 => 'cate',
	),
	'delete_with_user' => false,
) );
} );

